### PR TITLE
allow using the itunes episode for tagging

### PR DESCRIPTION
**Pull request by tbhi**

### CODE REVIEW

**Comment by manolomartinez** [comment]
LGTM. Could you please add this new placeholder to the relevant section in `greg.conf`?

**Comment by jvonhoff** [comment]
Anything needed to merge this PR?  The Marvel Wastelander podcasts (radio shows, really) don't lend themselves to get tagged correctly without manual intervention.  This itunes:episode tag would fix that right up.

**Comment by manolomartinez** [comment]
@tbhi, thanks a lot for this!
@jvonhoff please let me know if this doesn't work as it should.

**Comment by tbhi** [comment]
think `tag_track_num = {itunes_episode}`

**Comment by jvonhoff** [comment]
> think `tag_track_num = {itunes_episode}`

Works perfectly.  Should we also update the [greg.conf](https://github.com/manolomartinez/greg/blob/ca4a08e3c29d7038e6cec36b253aecc90163cc2f/greg/data/greg.conf#L111) file to say "tag_track_num" rather than just "tag_track"?

**Comment by manolomartinez** [comment]
> Should we also update the [greg.conf](https://github.com/manolomartinez/greg/blob/ca4a08e3c29d7038e6cec36b253aecc90163cc2f/greg/data/greg.conf#L111) file to say "tag_track_num" rather than just "tag_track"?

[Done](https://github.com/manolomartinez/greg/commit/2e4cbf074f1930f37468dc1ba6b675affe84dd25).

**Pull request merged**
